name: Build Explorer11

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build standalone executable
      run: dotnet publish -c Release -r win-x64 --self-contained -p:PublishReadyToRun=true
    
    - name: Upload publish folder
      uses: actions/upload-artifact@v4
      with:
        name: Explorer11-publish-folder
        path: bin/Release/net6.0-windows/win-x64/publish/**
        retention-days: 30
